services:
  api:
    build: ghcr.io/dnyaneshwar411/playstack-assessment:latest
    container_name: api
    restart: always
    ports:
      - "1993:1993"
    env_file:
      - ./server/.env
    command: node dist/index.cjs
